### ISSUE TITLE
Cant find files

### ISSUE THREAD

**Issue by geekjr** [thomasantony/msl-apollo-entry-guidance#1]
Hello,
While running the notebook in Google Colab, I get the following error

```
OSError: From: /content, could not find msl-aeroshell.png at either of these locations: ['msl-aeroshell.png', PosixPath('msl-aeroshell.png'), PosixPath('msl-aeroshell.png.jpg'), PosixPath('msl-aeroshell.png.jpeg'), PosixPath('msl-aeroshell.png.png'), PosixPath('msl-aeroshell.png.gif'), PosixPath('msl-aeroshell.png.ico')]
```

How do I fix this?

**Comment by geekjr** [comment]
Just to see where else i get that error, I put a random png called msl-areoshell.png. I also get it for C172.png.

**Comment by thomasantony** [comment]
Thanks for the heads up. I will add these images to the repository.
